// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    // keep syncd https://developer.android.com/jetpack/androidx/releases/compose-kotlin
//    ext.kotlin_version = '1.9.25'
//    ext.compose_version = '1.5.15'
//    ext.ksp_version = "1.9.25-1.0.20"



    ext.kotlin_version = '2.0.21'
    ext.compose_version = '2.0.21'
    ext.ksp_version = "2.0.21-1.0.28"

//    ext.kotlin_version = '2.1.0'
//    ext.compose_version = '2.1.0'
//    ext.ksp_version = "2.1.0-1.0.29"

    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.sentry:sentry-android-gradle-plugin:5.8.0'

        classpath "org.jlleitschuh.gradle:ktlint-gradle:12.1.0"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id 'com.google.devtools.ksp' version "$ksp_version" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' } // Markwon
        maven { url "https://plugins.gradle.org/m2/" } // ktlint
        maven { url "https://repo.spring.io/libs-milestone/" }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

apply plugin: "org.jlleitschuh.gradle.ktlint"

subprojects {
    apply plugin: "org.jlleitschuh.gradle.ktlint" // Version should be inherited from parent
    
    // Optionally configure plugin
    ktlint {
       debug = true
    }
}

ktlint {
    version = "0.22.0"
    debug = true
    verbose = true
    android = true
    outputToConsole = true
    outputColorName = "RED"
    ignoreFailures = true
    enableExperimentalRules = true
    reporters {
        reporter "plain"
        reporter "checkstyle"
    }
    kotlinScriptAdditionalPaths {
        include fileTree("scripts/")
    }
    filter {
        exclude("**/generated/**")
        include("**/kotlin/**")
    }
}
